using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;


namespace EgmGenerator.Models
{
    class PackageTypeCodes
    {
        public static List<PackageType> GetPackageTypes()
        {
            List<PackageType> packageTypes = new List<PackageType>();
            packageTypes.AddRange(new List<PackageType>()
            {
new PackageType(){Code ="1A" ,Name ="Drum, steel "},
new PackageType(){Code ="1B" ,Name ="Drum, aluminium "},
new PackageType(){Code ="1D" ,Name ="Drum, plywood "},
new PackageType(){Code ="1G" ,Name ="Drum, fibre "},
new PackageType(){Code ="1W" ,Name ="Drum, wooden "},
new PackageType(){Code ="2C" ,Name ="Barrel, wooden "},
new PackageType(){Code ="3A" ,Name ="Jerrican, steel "},
new PackageType(){Code ="3H" ,Name ="Jerrican, plastic "},
new PackageType(){Code ="4A" ,Name ="Box, steel "},
new PackageType(){Code ="4B" ,Name ="Box, aluminium "},
new PackageType(){Code ="4C" ,Name ="Box, natural wood "},
new PackageType(){Code ="4D" ,Name ="Box, plywood "},
new PackageType(){Code ="4F" ,Name ="Box, reconstituted wood "},
new PackageType(){Code ="4G" ,Name ="Box, fibreboard "},
new PackageType(){Code ="4H" ,Name ="Box, plastic "},
new PackageType(){Code ="5H" ,Name ="Bag, woven plastic "},
new PackageType(){Code ="5L" ,Name ="Bag, textile"},
new PackageType(){Code ="5M" ,Name ="Bag, paper"},
new PackageType(){Code ="6H" ,Name ="Comp. pkg, plastic recept"},
new PackageType(){Code ="6P" ,Name ="Comp. pkg, glass recept. "},
new PackageType(){Code ="AA" ,Name ="Int. bulk cont., rigid pl"},
new PackageType(){Code ="AB" ,Name ="recept., fibre "},
new PackageType(){Code ="AC" ,Name ="recept., paper "},
new PackageType(){Code ="AD" ,Name ="recept., wooden "},
new PackageType(){Code ="AE" ,Name ="Aerosol"},
new PackageType(){Code ="AF" ,Name ="Pallet, modular, collars "},
new PackageType(){Code ="AG" ,Name ="Pallet, shrinkwrapped"},
new PackageType(){Code ="AH" ,Name ="Pallet, 100cms * 110cms "},
new PackageType(){Code ="AI" ,Name ="Clamshell "},
new PackageType(){Code ="AJ" ,Name ="Cone"},
new PackageType(){Code ="AM" ,Name ="Ampoule, non-protected "},
new PackageType(){Code ="AP" ,Name ="Ampoule, protected "},
new PackageType(){Code ="AT" ,Name ="Atomizer"},
new PackageType(){Code ="AV" ,Name ="Capsule "},
new PackageType(){Code ="BA" ,Name ="Barrel "},
new PackageType(){Code ="BB" ,Name ="Bobbin "},
new PackageType(){Code ="BC" ,Name ="Bottlecrate / bottlerack "},
new PackageType(){Code ="BD" ,Name ="Board "},
new PackageType(){Code ="BE" ,Name ="Bundle "},
new PackageType(){Code ="BF" ,Name ="Balloon, non-protected "},
new PackageType(){Code ="BG" ,Name ="Bag "},
new PackageType(){Code ="BH" ,Name ="Bunch "},
new PackageType(){Code ="BI" ,Name ="Bin "},
new PackageType(){Code ="BJ" ,Name ="Bucket "},
new PackageType(){Code ="BK" ,Name ="Basket "},
new PackageType(){Code ="BL" ,Name ="Bale, compressed "},
new PackageType(){Code ="BM" ,Name ="Basin "},
new PackageType(){Code ="BN" ,Name ="Bale, non-compressed "},
new PackageType(){Code ="BO" ,Name ="Bottle, non-protected, cy"},
new PackageType(){Code ="BP" ,Name ="Balloon, protected "},
new PackageType(){Code ="BQ" ,Name ="Bottle, protected cylindr"},
new PackageType(){Code ="BR" ,Name ="Bar "},
new PackageType(){Code ="BS" ,Name ="Bottle, non-protected, bu"},
new PackageType(){Code ="BT" ,Name ="Bolt "},
new PackageType(){Code ="BU" ,Name ="Butt "},
new PackageType(){Code ="BV" ,Name ="Bottle, protected bulbous"},
new PackageType(){Code ="BW" ,Name ="Box, for liquids"},
new PackageType(){Code ="BX" ,Name ="Box "},
new PackageType(){Code ="BY" ,Name ="Board, in bundle/bunch/tr"},
new PackageType(){Code ="BZ" ,Name ="Bars, in bundle/bunch/tru"},
new PackageType(){Code ="CA" ,Name ="Can, rectangular "},
new PackageType(){Code ="CB" ,Name ="Crate, beer "},
new PackageType(){Code ="CC" ,Name ="Churn "},
new PackageType(){Code ="CD" ,Name ="Can, with handle and spou"},
new PackageType(){Code ="CE" ,Name ="Creel "},
new PackageType(){Code ="CF" ,Name ="Coffer "},
new PackageType(){Code ="CG" ,Name ="Cage "},
new PackageType(){Code ="CH" ,Name ="Chest "},
new PackageType(){Code ="CI" ,Name ="Canister "},
new PackageType(){Code ="CJ" ,Name ="Coffin"},
new PackageType(){Code ="CK" ,Name ="Cask "},
new PackageType(){Code ="CL" ,Name ="Coil "},
new PackageType(){Code ="CM" ,Name ="Card "},
new PackageType(){Code ="CN" ,Name ="cont., not otherwise spec"},
new PackageType(){Code ="CO" ,Name ="Carboy, non-protected "},
new PackageType(){Code ="CP" ,Name ="Carboy, protected "},
new PackageType(){Code ="CQ" ,Name ="Cartridge"},
new PackageType(){Code ="CR" ,Name ="Crate"},
new PackageType(){Code ="CS" ,Name ="Case"},
new PackageType(){Code ="CT" ,Name ="Carton "},
new PackageType(){Code ="CU" ,Name ="Cup "},
new PackageType(){Code ="CV" ,Name ="Cover"},
new PackageType(){Code ="CW" ,Name ="Cage, roll"},
new PackageType(){Code ="CX" ,Name ="Can, cylindrical "},
new PackageType(){Code ="CY" ,Name ="Cylinder "},
new PackageType(){Code ="CZ" ,Name ="Canvas "},
new PackageType(){Code ="DA" ,Name ="Crate, multiple layer, pl"},
new PackageType(){Code ="DB" ,Name ="Crate, multiple layer, wo"},
new PackageType(){Code ="DC" ,Name ="Crate, multiple layer, ca"},
new PackageType(){Code ="DG" ,Name ="Cage, Commonwealth Handli"},
new PackageType(){Code ="DI" ,Name ="Drum, iron "},
new PackageType(){Code ="DJ" ,Name ="Demijohn, non-protected "},
new PackageType(){Code ="DK" ,Name ="Crate, bulk, cardboard "},
new PackageType(){Code ="DL" ,Name ="Crate, bulk, plastic "},
new PackageType(){Code ="DM" ,Name ="Crate, bulk, wooden "},
new PackageType(){Code ="DN" ,Name ="Dispenser"},
new PackageType(){Code ="DP" ,Name ="Demijohn, protected "},
new PackageType(){Code ="DR" ,Name ="Drum "},
new PackageType(){Code ="DS" ,Name ="Tray, one layer no cover,"},
new PackageType(){Code ="DT" ,Name ="Tray, one layer no cover,"},
new PackageType(){Code ="DU" ,Name ="Tray, one layer no cover,"},
new PackageType(){Code ="DV" ,Name ="Tray, one layer no cover,"},
new PackageType(){Code ="DW" ,Name ="Tray, two layers no cover"},
new PackageType(){Code ="DX" ,Name ="Tray, two layers no cover"},
new PackageType(){Code ="DY" ,Name ="Tray, two layers no cover"},
new PackageType(){Code ="EC" ,Name ="Bag, plastic"},
new PackageType(){Code ="ED" ,Name ="Case, with pallet base "},
new PackageType(){Code ="EE" ,Name ="Case, with pallet base, w"},
new PackageType(){Code ="EF" ,Name ="Case, with pallet base, c"},
new PackageType(){Code ="EG" ,Name ="Case, with pallet base, p"},
new PackageType(){Code ="EH" ,Name ="Case, with pallet base, m"},
new PackageType(){Code ="EI" ,Name ="Case, isothermic "},
new PackageType(){Code ="EN" ,Name ="Envelope "},
new PackageType(){Code ="FC" ,Name ="Crate, fruit "},
new PackageType(){Code ="FD" ,Name ="Crate, framed "},
new PackageType(){Code ="FI" ,Name ="Firkin "},
new PackageType(){Code ="FL" ,Name ="Flask "},
new PackageType(){Code ="FO" ,Name ="Footlocker "},
new PackageType(){Code ="FP" ,Name ="Filmpack "},
new PackageType(){Code ="FR" ,Name ="Frame "},
new PackageType(){Code ="FT" ,Name ="Foodtainer "},
new PackageType(){Code ="FX" ,Name ="Bag, flexible cont."},
new PackageType(){Code ="GB" ,Name ="Bottle, gas "},
new PackageType(){Code ="GI" ,Name ="Girder "},
new PackageType(){Code ="GR" ,Name ="recept., glass "},
new PackageType(){Code ="GZ" ,Name ="Girders, in bundle/bunch/"},
new PackageType(){Code ="HA" ,Name ="Basket, with handle, plas"},
new PackageType(){Code ="HB" ,Name ="Basket, with handle, wood"},
new PackageType(){Code ="HC" ,Name ="Basket, with handle, card"},
new PackageType(){Code ="HG" ,Name ="Hogshead "},
new PackageType(){Code ="HR" ,Name ="Hamper "},
new PackageType(){Code ="IA" ,Name ="Package, display, wooden "},
new PackageType(){Code ="IB" ,Name ="Package, display, cardboa"},
new PackageType(){Code ="IC" ,Name ="Package, display, plastic"},
new PackageType(){Code ="ID" ,Name ="Package, display, metal "},
new PackageType(){Code ="IE" ,Name ="Package, show "},
new PackageType(){Code ="IF" ,Name ="Package, flow "},
new PackageType(){Code ="IG" ,Name ="Package, paper wrapped "},
new PackageType(){Code ="IH" ,Name ="Drum, plastic "},
new PackageType(){Code ="IK" ,Name ="Package, cardboard, with "},
new PackageType(){Code ="IN" ,Name ="Ingot "},
new PackageType(){Code ="IZ" ,Name ="Ingots, in bundle/bunch/t"},
new PackageType(){Code ="JC" ,Name ="Jerrican, rectangular "},
new PackageType(){Code ="JG" ,Name ="Jug "},
new PackageType(){Code ="JR" ,Name ="Jar "},
new PackageType(){Code ="JT" ,Name ="Jutebag "},
new PackageType(){Code ="JY" ,Name ="Jerrican, cylindrical "},
new PackageType(){Code ="KG" ,Name ="Keg "},
new PackageType(){Code ="LG" ,Name ="Log "},
new PackageType(){Code ="LT" ,Name ="Lot "},
new PackageType(){Code ="LV" ,Name ="Liftvan "},
new PackageType(){Code ="LZ" ,Name ="Logs, in bundle/bunch/tru"},
new PackageType(){Code ="MB" ,Name ="Bag, multiply"},
new PackageType(){Code ="MC" ,Name ="Crate, milk"},
new PackageType(){Code ="MR" ,Name ="recept., metal "},
new PackageType(){Code ="MS" ,Name ="Sack, multi-wall"},
new PackageType(){Code ="MT" ,Name ="Mat "},
new PackageType(){Code ="MW" ,Name ="recept., plastic wrapped"},
new PackageType(){Code ="MX" ,Name ="Matchbox "},
new PackageType(){Code ="NA" ,Name ="Not available"},
new PackageType(){Code ="NE" ,Name ="Unpacked or unpackaged "},
new PackageType(){Code ="NF" ,Name ="Unpacked or unpackaged, s"},
new PackageType(){Code ="NG" ,Name ="Unpacked or unpackaged, m"},
new PackageType(){Code ="NS" ,Name ="Nest"},
new PackageType(){Code ="NT" ,Name ="Net"},
new PackageType(){Code ="NU" ,Name ="Net, tube, plastic"},
new PackageType(){Code ="NV" ,Name ="Net, tube, textile "},
new PackageType(){Code ="PA" ,Name ="Packet "},
new PackageType(){Code ="PB" ,Name ="Pallet, box "},
new PackageType(){Code ="PC" ,Name ="Parcel "},
new PackageType(){Code ="PD" ,Name ="Pallet, modular, collars "},
new PackageType(){Code ="PE" ,Name ="Pallet, modular, collars "},
new PackageType(){Code ="PF" ,Name ="Pen"},
new PackageType(){Code ="PG" ,Name ="Plate "},
new PackageType(){Code ="PH" ,Name ="Pitcher "},
new PackageType(){Code ="PI" ,Name ="Pipe"},
new PackageType(){Code ="PJ" ,Name ="Punnet"},
new PackageType(){Code ="PK" ,Name ="Package "},
new PackageType(){Code ="PL" ,Name ="Pail "},
new PackageType(){Code ="PN" ,Name ="Plank "},
new PackageType(){Code ="PO" ,Name ="Pouch "},
new PackageType(){Code ="PR" ,Name ="recept., plastic "},
new PackageType(){Code ="PT" ,Name ="Pot "},
new PackageType(){Code ="PU" ,Name ="Tray "},
new PackageType(){Code ="PV" ,Name ="Pipes, in bundle/bunch/tr"},
new PackageType(){Code ="PX" ,Name ="Pallet "},
new PackageType(){Code ="PY" ,Name ="Plates, in bundle/bunch/t"},
new PackageType(){Code ="PZ" ,Name ="Planks, in bundle/bunch/t"},
new PackageType(){Code ="QA" ,Name ="Drum, steel, non-removabl"},
new PackageType(){Code ="QB" ,Name ="Drum, steel, removable he"},
new PackageType(){Code ="QC" ,Name ="Drum, aluminium, non-remo"},
new PackageType(){Code ="QD" ,Name ="Drum, aluminium, removabl"},
new PackageType(){Code ="QF" ,Name ="Drum, plastic, non-remova"},
new PackageType(){Code ="QG" ,Name ="Drum, plastic, removable "},
new PackageType(){Code ="QH" ,Name ="Barrel, wooden, bung type"},
new PackageType(){Code ="QJ" ,Name ="Barrel, wooden, removable"},
new PackageType(){Code ="QK" ,Name ="Jerrican, steel, non-remo"},
new PackageType(){Code ="QL" ,Name ="Jerrican, steel, removabl"},
new PackageType(){Code ="QM" ,Name ="Jerrican, plastic, non-re"},
new PackageType(){Code ="QN" ,Name ="Jerrican, plastic, remova"},
new PackageType(){Code ="QP" ,Name ="Box, wooden, natural wood"},
new PackageType(){Code ="QQ" ,Name ="Box, wooden, natural wood"},
new PackageType(){Code ="QR" ,Name ="Box, plastic, expanded "},
new PackageType(){Code ="QS" ,Name ="Box, plastic, solid "},
new PackageType(){Code ="RD" ,Name ="Rod"},
new PackageType(){Code ="RG" ,Name ="Ring "},
new PackageType(){Code ="RJ" ,Name ="Rack, clothing hanger"},
new PackageType(){Code ="RK" ,Name ="Rack"},
new PackageType(){Code ="RL" ,Name ="Reel "},
new PackageType(){Code ="RO" ,Name ="Roll "},
new PackageType(){Code ="RT" ,Name ="Rednet "},
new PackageType(){Code ="RZ" ,Name ="Rods, in bundle/bunch/tru"},
new PackageType(){Code ="SA" ,Name ="Sack "},
new PackageType(){Code ="SB" ,Name ="Slab"},
new PackageType(){Code ="SC" ,Name ="Crate, shallow "},
new PackageType(){Code ="SD" ,Name ="Spindle "},
new PackageType(){Code ="SE" ,Name ="Sea-chest "},
new PackageType(){Code ="SH" ,Name ="Sachet "},
new PackageType(){Code ="SI" ,Name ="Skid "},
new PackageType(){Code ="SK" ,Name ="Case, skeleton "},
new PackageType(){Code ="SL" ,Name ="Slipsheet "},
new PackageType(){Code ="SM" ,Name ="Sheetmetal "},
new PackageType(){Code ="SO" ,Name ="Spool"},
new PackageType(){Code ="SP" ,Name ="Sheet, plastic wrapping "},
new PackageType(){Code ="SS" ,Name ="Case, steel "},
new PackageType(){Code ="ST" ,Name ="Sheet "},
new PackageType(){Code ="SU" ,Name ="Suitcase "},
new PackageType(){Code ="SV" ,Name ="Envelope, steel "},
new PackageType(){Code ="SW" ,Name ="Shrinkwrapped "},
new PackageType(){Code ="SX" ,Name ="X Set "},
new PackageType(){Code ="SY" ,Name ="Sleeve"},
new PackageType(){Code ="SZ" ,Name ="Sheets, in bundle/bunch/t"},
new PackageType(){Code ="TB" ,Name ="Tub "},
new PackageType(){Code ="TC" ,Name ="Tea-chest "},
new PackageType(){Code ="TD" ,Name ="Tube, collapsible "},
new PackageType(){Code ="TI" ,Name ="Tierce "},
new PackageType(){Code ="TK" ,Name ="Tank, rectangular "},
new PackageType(){Code ="TL" ,Name ="Tub, with lid "},
new PackageType(){Code ="TN" ,Name ="Tin "},
new PackageType(){Code ="TO" ,Name ="Tun "},
new PackageType(){Code ="TR" ,Name ="Trunk "},
new PackageType(){Code ="TS" ,Name ="Truss "},
new PackageType(){Code ="TU" ,Name ="Tube "},
new PackageType(){Code ="TV" ,Name ="Tube, with nozzle "},
new PackageType(){Code ="TY" ,Name ="Tank, cylindrical "},
new PackageType(){Code ="TZ" ,Name ="Tubes, in bundle/bunch/tr"},
new PackageType(){Code ="UC" ,Name ="Uncaged "},
new PackageType(){Code ="VA" ,Name ="Vat "},
new PackageType(){Code ="VG" ,Name ="Bulk, gas (at 1031 mbar a"},
new PackageType(){Code ="VI" ,Name ="Vial "},
new PackageType(){Code ="VK" ,Name ="Vanpack "},
new PackageType(){Code ="VL" ,Name ="Bulk, liquid "},
new PackageType(){Code ="VO" ,Name ="Bulk, solid, large partic"},
new PackageType(){Code ="VP" ,Name ="Vacuum-packed "},
new PackageType(){Code ="VQ" ,Name ="Bulk, liquefied gas (at a"},
new PackageType(){Code ="VR" ,Name ="Bulk, solid, granular par"},
new PackageType(){Code ="VY" ,Name ="Bulk, solid, fine particl"},
new PackageType(){Code ="WA" ,Name ="Int. bulk cont."},
new PackageType(){Code ="WB" ,Name ="Wickerbottle"},
new PackageType(){Code ="WC" ,Name ="Int. bulk cont., steel"},
new PackageType(){Code ="WD" ,Name ="Int. bulk cont., aluminiu"},
new PackageType(){Code ="WF" ,Name ="Int. bulk cont., metal"},
new PackageType(){Code ="WG" ,Name ="Int. bulk cont., steel, p"},
new PackageType(){Code ="WH" ,Name ="Int. bulk cont., aluminiu"},
new PackageType(){Code ="WJ" ,Name ="Int. bulk cont., metal, p"},
new PackageType(){Code ="WK" ,Name ="Int. bulk cont., steel, l"},
new PackageType(){Code ="WL" ,Name ="Int. bulk cont., aluminiu"},
new PackageType(){Code ="WM" ,Name ="Int. bulk cont., metal, l"},
new PackageType(){Code ="WN" ,Name ="Int. bulk cont., woven pl"},
new PackageType(){Code ="WP" ,Name ="Int. bulk cont., woven pl"},
new PackageType(){Code ="WQ" ,Name ="Int. bulk cont., woven pl"},
new PackageType(){Code ="WR" ,Name ="Int. bulk cont., woven pl"},
new PackageType(){Code ="WS" ,Name ="Int. bulk cont., plastic "},
new PackageType(){Code ="WT" ,Name ="Int. bulk cont., textile "},
new PackageType(){Code ="WU" ,Name ="Int. bulk cont., natural "},
new PackageType(){Code ="WV" ,Name ="Int. bulk cont., textile,"},
new PackageType(){Code ="WW" ,Name ="Int. bulk cont., textile,"},
new PackageType(){Code ="WX" ,Name ="Int. bulk cont., textile,"},
new PackageType(){Code ="WY" ,Name ="Int. bulk cont., plywood,"},
new PackageType(){Code ="WZ" ,Name ="Int. bulk cont., reconsti"},
new PackageType(){Code ="XA" ,Name ="Bag, woven plastic, witho"},
new PackageType(){Code ="XB" ,Name ="Bag, woven plastic, sift "},
new PackageType(){Code ="XC" ,Name ="Bag, woven plastic, water"},
new PackageType(){Code ="XD" ,Name ="Bag, plastics film "},
new PackageType(){Code ="XF" ,Name ="Bag, textile, without inn"},
new PackageType(){Code ="XG" ,Name ="Bag, textile, sift proof "},
new PackageType(){Code ="XH" ,Name ="Bag, textile, water resis"},
new PackageType(){Code ="XJ" ,Name ="Bag, paper, multi-wall "},
new PackageType(){Code ="XK" ,Name ="Bag, paper, multi-wall, w"},
new PackageType(){Code ="YA" ,Name ="Comp. pkg, plastic recept"},
new PackageType(){Code ="YB" ,Name ="Comp. pkg, plastic recept"},
new PackageType(){Code ="YC" ,Name ="Comp. pkg, plastic recept"},
new PackageType(){Code ="YD" ,Name ="Comp. pkg, plastic recept"},
new PackageType(){Code ="YF" ,Name ="Comp. pkg, plastic recept"},
new PackageType(){Code ="YG" ,Name ="Comp. pkg, plastic recept"},
new PackageType(){Code ="YH" ,Name ="Comp. pkg, plastic recept"},
new PackageType(){Code ="YJ" ,Name ="Comp. pkg, plastic recept"},
new PackageType(){Code ="YK" ,Name ="Comp. pkg, plastic recept"},
new PackageType(){Code ="YL" ,Name ="Comp. pkg, plastic recept"},
new PackageType(){Code ="YM" ,Name ="Comp. pkg, plastic recept"},
new PackageType(){Code ="YN" ,Name ="Comp. pkg, glass recept. "},
new PackageType(){Code ="YP" ,Name ="Comp. pkg, glass recept. "},
new PackageType(){Code ="YQ" ,Name ="Comp. pkg, glass recept. "},
new PackageType(){Code ="YR" ,Name ="Comp. pkg, glass recept. "},
new PackageType(){Code ="YS" ,Name ="Comp. pkg, glass recept. "},
new PackageType(){Code ="YT" ,Name ="Comp. pkg, glass recept. "},
new PackageType(){Code ="YV" ,Name ="Comp. pkg, glass recept. "},
new PackageType(){Code ="YW" ,Name ="Comp. pkg, glass recept. "},
new PackageType(){Code ="YX" ,Name ="Comp. pkg, glass recept. "},
new PackageType(){Code ="YY" ,Name ="Comp. pkg, glass recept. "},
new PackageType(){Code ="YZ" ,Name ="Comp. pkg, glass recept. "},
new PackageType(){Code ="ZA" ,Name ="Int. bulk cont., paper, m"},
new PackageType(){Code ="ZB" ,Name ="Bag, large"},
new PackageType(){Code ="ZC" ,Name ="Int. bulk cont., paper, m"},
new PackageType(){Code ="ZD" ,Name ="Int. bulk cont., rigid pl"},
new PackageType(){Code ="ZF" ,Name ="Int. bulk cont., rigid pl"},
new PackageType(){Code ="ZH" ,Name ="Int. bulk cont., rigid pl"},
new PackageType(){Code ="ZJ" ,Name ="Int. bulk cont., rigid pl"},
new PackageType(){Code ="ZK" ,Name ="Int. bulk cont., rigid pl"},
new PackageType(){Code ="ZL" ,Name ="Int. bulk cont., Comp., r"},
new PackageType(){Code ="ZM" ,Name ="Int. bulk cont., Comp., f"},
new PackageType(){Code ="ZN" ,Name ="Int. bulk cont., Comp., r"},
new PackageType(){Code ="ZP" ,Name ="Int. bulk cont., Comp., f"},
new PackageType(){Code ="ZQ" ,Name ="Int. bulk cont., Comp., r"},
new PackageType(){Code ="ZR" ,Name ="Int. bulk cont., Comp., f"},
new PackageType(){Code ="ZT" ,Name ="Int. bulk cont., fibreboa"},
new PackageType(){Code ="ZU" ,Name ="Int. bulk cont., flexible"},
new PackageType(){Code ="ZV" ,Name ="Int. bulk cont., metal, o"},
new PackageType(){Code ="ZW" ,Name ="Int. bulk cont., natural "},
new PackageType(){Code ="ZY" ,Name ="Int. bulk cont., reconsti"},
new PackageType(){Code ="ZZ" ,Name ="Packed in above"},

            });
           packageTypes.ForEach(a => a.Name = a.Name.ToLower());
            return packageTypes.OrderBy(a=>a.Code).ToList();
        }
    }
}
